//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactExample.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLogin
    {
        public string LoginId { get; set; }
        public string Pwd { get; set; }
        public string name { get; set; }
        public string LoginType { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    }
}
